
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // process.env (not env()) so `prisma generate` works in CI when vars are unset
    url: process.env.DATABASE_URL,
    directUrl: process.env.DIRECT_URL,
  },
});
